apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: login
  name: {{ .Values.login.name }}
spec:
  replicas: {{ .Values.login.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: slurm
      app.kubernetes.io/component: login
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: slurm
        app.kubernetes.io/component: login
    spec:
      containers:
        - args:
            - login
          image: {{ .Values.slurmImage }}
          name: login
          ports:
            - containerPort: 22
          volumeMounts:
            - mountPath: {{ .Values.storage.mountPath }}
              name: slurm-jobdir
            - mountPath: /etc/slurm/
              name: slurm-config-volume
            - mountPath: /tmp/munge.key
              name: munge-key-secret
              subPath: munge.key
            - mountPath: /etc/ssh/sshd_config
              subPath: sshd_config
              name: sshd-config-configmap
            - name: authorized-keys
              mountPath: /tmp/authorized_keys
              subPath: authorized_keys
          resources: {}
      hostname: login
      dnsConfig:
        searches:
          - slurmd.default.svc.cluster.local
      restartPolicy: Always
      volumes:
        - name: slurm-jobdir
          persistentVolumeClaim:
            claimName: {{ .Values.storage.claimName }}
        - name: slurm-config-volume
          configMap:
            name: {{ .Values.configmaps.slurmConf }}
        - name: sshd-config-configmap
          configMap:
            name: {{ .Values.configmaps.sshdConfig }}
        - name: munge-key-secret
          secret:
            secretName: {{ .Values.secrets.mungeKey }}
            defaultMode: 0400
        - name: authorized-keys
          configMap:
            name: {{ .Values.configmaps.authorizedKeys }}
