---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.claimName }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}