---
# A default storageclass must be present
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claimName}}
  namespace: {{ .Values.serverNamespace }}
spec:
  storageClassName: {{ .Values.backingStorageClass }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storageCapacity }}
---
apiVersion: nfs.rook.io/v1alpha1
kind: NFSServer
metadata:
  name: {{ .Values.serverName }}
  namespace: {{ .Values.serverNamespace }}
spec:
  replicas: 1
  exports:
  - name: {{ .Values.shareName }}
    server:
      accessMode: ReadWrite
      squash: "none"
    # A Persistent Volume Claim must be created before creating NFS CRD instance.
    persistentVolumeClaim:
      claimName: {{ .Values.claimName }}
  # A key/value list of annotations
  annotations:
    rook: nfs
---
