#!/usr/bin/bash
set -euo pipefail

echo "$(date) Resume invoked $0 $*" >> /var/log/slurm/power_save.log

echo "Arguments: $* $0 $1" >> /var/log/slurm/power_save.log

hosts=$(scontrol show hostnames $1) # this is purely a textual expansion, doens't depend on defined nodes
echo "Powering up hosts: $hosts" >> /var/log/slurm/power_save.log
for host in $hosts
do
   echo "Creating $host" >> /var/log/slurm/power_save.log
   touch tmpfile.yml
   sed s/SLURMD_NODENAME/$host/ /etc/slurm/slurmd-pod-template.yml > tmpfile.yml
   echo "sed successful" >> /var/log/slurm/power_save.log
   kubectl create -f tmpfile.yml &> /var/log/slurm/power_save.log
   echo "done" >> /var/log/slurm/power_save.log
done
