#!/usr/bin/bash

echo "$(date) Resume invoked $0 $*" &>> /var/log/slurm/power_save.log

APISERVER=https://kubernetes.default.svc
SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
TOKEN=$(cat ${SERVICEACCOUNT}/token)
CACERT=${SERVICEACCOUNT}/ca.crt

hosts=$(scontrol show hostnames $1) # this is purely a textual expansion, doens't depend on defined nodes
for host in $hosts
do
   ( sed s/SLURMD_NODENAME/$host/ /etc/slurm/slurmd-pod-template.yml | \
   kubectl --server $APISERVER --token $TOKEN --certificate-authority $CACERT create -f - )
done